dbfile: db/wartracker.db
scratch: _scratch
tessdata: /Users/erumer/src/github.com/tesseract-ocr/tessdata
mapdir: config/scanner/maps
languages:
httpAddr: ":3001"
httpsAddr: ":3000"
cert: "~/.lego/certificates/_.ennead.games.crt"
key: "~/.lego/certificates/_.ennead.games.key"
